/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as CronjobsRouteImport } from './routes/cronjobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatWorkspaceIdRouteImport } from './routes/chat.$workspaceId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsRoute = CronjobsRouteImport.update({
  id: '/cronjobs',
  path: '/cronjobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatWorkspaceIdRoute = ChatWorkspaceIdRouteImport.update({
  id: '/chat/$workspaceId',
  path: '/chat/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronjobs': typeof CronjobsRoute
  '/tasks': typeof TasksRoute
  '/chat/$workspaceId': typeof ChatWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronjobs': typeof CronjobsRoute
  '/tasks': typeof TasksRoute
  '/chat/$workspaceId': typeof ChatWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cronjobs': typeof CronjobsRoute
  '/tasks': typeof TasksRoute
  '/chat/$workspaceId': typeof ChatWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cronjobs' | '/tasks' | '/chat/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cronjobs' | '/tasks' | '/chat/$workspaceId'
  id: '__root__' | '/' | '/cronjobs' | '/tasks' | '/chat/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CronjobsRoute: typeof CronjobsRoute
  TasksRoute: typeof TasksRoute
  ChatWorkspaceIdRoute: typeof ChatWorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs': {
      id: '/cronjobs'
      path: '/cronjobs'
      fullPath: '/cronjobs'
      preLoaderRoute: typeof CronjobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$workspaceId': {
      id: '/chat/$workspaceId'
      path: '/chat/$workspaceId'
      fullPath: '/chat/$workspaceId'
      preLoaderRoute: typeof ChatWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CronjobsRoute: CronjobsRoute,
  TasksRoute: TasksRoute,
  ChatWorkspaceIdRoute: ChatWorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
